---
apiVersion: v1
data:
  ca-bundle.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDXTCCAkWgAwIBAgIIKI5nU7kPCmswDQYJKoZIhvcNAQELBQAwUjFQME4GA1UE
    AwxHb3BlbnNoaWZ0LWt1YmUtY29udHJvbGxlci1tYW5hZ2VyLW9wZXJhdG9yX2Nz
    ci1zaWduZXItc2lnbmVyQDE1ODY5NDIzNDgwHhcNMjAwNDE1MDkzMjM4WhcNMjAw
    NTE1MDkzMjM5WjAmMSQwIgYDVQQDDBtrdWJlLWNzci1zaWduZXJfQDE1ODY5NDMx
    NTkwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCzfLqyRV0moaSngW3S
    R4xKrwtle7mDyAkDto62PDf1fQiMRZicHZ4ep64CdlbIpj3Xk6rjBKOgU9CvYW9U
    aGooczhpEKb26+95RLaPU3a7PmSh9OYQRfJsR7rzGbqtVdHBQFnEGUBjmBj/PBgu
    BWF4puVraz8I9h3CsxIqDcyyLbVL+TCQKdxBUhAphk4YnI9OGXHpHx26kmttGLwx
    ax1iYfCCSfJ54r+2a3wpbI9esgZVqB5YsNYxWddcI8z+gF2vvtSar06pPppkPkH+
    pNCTYebo5CG70FarqwKh1kW2XK0WduvOoZJ1VlG54c2W524YRwPAViz5NfhN8zxt
    tMHhAgMBAAGjYzBhMA4GA1UdDwEB/wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MB0G
    A1UdDgQWBBT/qiYUyOEZoM6UsdcU0W9nSaVhmTAfBgNVHSMEGDAWgBTsHA21Ve50
    GWKMssuJUtSw/5gw8DANBgkqhkiG9w0BAQsFAAOCAQEAfYxXaf3opAGfpyb8UAm0
    5lWuvVQb2aDtI3+d5CRMB64w2DxVu8clLkfwl6hcWU6JNPN+aMyYW6y5PmtWmPcK
    LMVF91zRnrO0MHhNGNjNqQkLJh9YHDXEtfBOTzc51FDyeLdfYoJhBYMrqbATMoj6
    QqoCxljrYxiHZCutjXdqOlI7Gw+5JkQMgjop7sArOjMLI/YN0PZ5UkZ169EUIbSS
    FdRAGTee7RtuxpzwskOKqc0UaU61esKgkDsUcJnaAimXo+8/0yum8kJ4U9W0Gvhw
    HQhyo0JfedOHl4XNXZxhsaqUB71BFIFkrA10pyPILVf32HJaMgXK/6+pi9GqMCF7
    OQ==
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDgjCCAmqgAwIBAgIBATANBgkqhkiG9w0BAQsFADBSMVAwTgYDVQQDDEdvcGVu
    c2hpZnQta3ViZS1jb250cm9sbGVyLW1hbmFnZXItb3BlcmF0b3JfY3NyLXNpZ25l
    ci1zaWduZXJAMTU4Njk0MjM0ODAeFw0yMDA0MTUwOTE5MDdaFw0yMDA2MTQwOTE5
    MDhaMFIxUDBOBgNVBAMMR29wZW5zaGlmdC1rdWJlLWNvbnRyb2xsZXItbWFuYWdl
    ci1vcGVyYXRvcl9jc3Itc2lnbmVyLXNpZ25lckAxNTg2OTQyMzQ4MIIBIjANBgkq
    hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxQk3qP+njqW5MuzMtEKXOAwB+z9R0Ww/
    /PM8cHIuL6OkBUkYNO0zycfcq0algNNUPflVcR2D+9dkfEFwraPjvEzWWO0/4k9v
    90YcSek2TsU9VR9iz0tW/itMkAFiX1KPTNjN6IGixtnwbxZuD0k5uAUc3/yi3fWX
    gSFBqryC39uG3Hr05C6cJZ/lwAAdQi41lVOeoASrtSnJhJP6Ux09LiFQp/Ba9vI+
    C2uMdX3hg5Wzt/k7+vRK0/sK3t/HUoBemd7Z/Fyf3a6dmcIpMtZjUxv2DhJ1vU1B
    UtDyyEk6ezAvXHqMuJ6WzvxmlBrPVK+Iq3Nt63gp5vEeO+GVjiofNwIDAQABo2Mw
    YTAOBgNVHQ8BAf8EBAMCAqQwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQU7BwN
    tVXudBlijLLLiVLUsP+YMPAwHwYDVR0jBBgwFoAU7BwNtVXudBlijLLLiVLUsP+Y
    MPAwDQYJKoZIhvcNAQELBQADggEBAJr3gqHEoe+LtXT6CYokwRgQvSTHS2NWccS7
    9XZYNQfh3miA++PN73WCBSQPr69rEZEnWSXK1Ko5joswEdbHFObk1ejunZ24AKDL
    /4yzS9C7yfnfb6TTixYbyUKU5sPQnpvDTx3zj7MEB4L3Chxud9VLz2DK/zW9xhbl
    xqisK4Yhkf1rRs/Czv7jRUeKmTzvvkYSYtVSNWBEUUr9z/FGp4g3eoO/NXJLM0ey
    87llO+IUyRBMZ/R1Jdr/XU5ncOWXMwxDnLlwgds/x5j71lMsQrqMjEMPZN73nj7K
    797GeYIM5Knmtprh8iGe0zyYxqW3S8ZwfCZKVN5GUGY6tJGnvPc=
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  name: kubelet-serving-ca-bundle
---
apiVersion: v1
data:
  service-ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDSjCCAjKgAwIBAgIBATANBgkqhkiG9w0BAQsFADA2MTQwMgYDVQQDDCtvcGVu
    c2hpZnQtc2VydmljZS1zZXJ2aW5nLXNpZ25lckAxNTg2ODc3MzE1MB4XDTIwMDQx
    NDE1MTUxNVoXDTIxMDQxNDE1MTUxNlowNjE0MDIGA1UEAwwrb3BlbnNoaWZ0LXNl
    cnZpY2Utc2VydmluZy1zaWduZXJAMTU4Njg3NzMxNTCCASIwDQYJKoZIhvcNAQEB
    BQADggEPADCCAQoCggEBALJPhSsA74ALNeXy6QtxOe8pke8goIRrwl6BXbv60UGV
    YqQ6MYsSs/3Ud1fxjCz8gHXg75H7jTT3bC9wN4xpnqGDgYu4VdFWhfuu/sCs3xM8
    Yk7m7jDbd3AlXPBPoojYcGKS1giBiqc8TIqR5+ERjKrf6Lm3pYKBxNspIX+AXP+4
    MwItYuD6qdyzQXd4Q6I03NTAG1Jr8TQ1jDh6GO7HA+bkggJkUPlvAUnydivjy014
    StNbhfMmo+PkxlhCC+dI6rCqQW9XGBIbhmGv45ct/QcPsFgliq0vQhknWWavcvuf
    FgPJxqnZ24SzMjoe+0bL0bWtn90xbtmF7ZWkej29GJsCAwEAAaNjMGEwDgYDVR0P
    AQH/BAQDAgKkMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFL7gmz3+o1e+8mgx
    ecuo1ovklMD3MB8GA1UdIwQYMBaAFL7gmz3+o1e+8mgxecuo1ovklMD3MA0GCSqG
    SIb3DQEBCwUAA4IBAQBg4Nj/NiCErZq3+16Izlkx/R5GJy8DDm4D7IWcy/VukDQL
    C4PaMliRUqvokyjf4PrYx1jyHGlOxrklq9WhbUm/qkWRgeID0g+cQDYpiGHS3Ghs
    syuW8+tOgQp9fg9WphJaj3CPQvnTkIItZd1mKZySmEROfzVvFJCWWRCZmdEd1nFN
    iaPr3CBmNTgodv1L3RsGd9ng+okJZDR7ztGJ3aHX67JIXu68IiJByeot/OjVO2I+
    dtkQYg6LTilpnPOkG7PoCaMC5j6R6p8u2Qqk8nggz7vcGDOt2XAGMf042eQS/VOy
    3dPLu5m/Of7ggO9aHBPLK9p8Mz1Cm0AyDoJRfUOP
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  annotations:
    service.alpha.openshift.io/inject-cabundle: "true"
  name: serving-certs-ca-bundle
---
apiVersion: v1
data:
  etcd-client-ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKakNDQWc2Z0F3SUJBZ0lJWjNSeS9uUzFsVWd3RFFZSktvWklodmNOQVFFTEJRQXdNVEVTTUJBR0ExVUUKQ3hNSmIzQmxibk5vYVdaME1Sc3dHUVlEVlFRREV4SmxkR05rTFcxbGRISnBZeTF6YVdkdVpYSXdIaGNOTWpBdwpOREUwTVRRd05qQTRXaGNOTXpBd05ERXlNVFF3TmpBNFdqQXhNUkl3RUFZRFZRUUxFd2x2Y0dWdWMyaHBablF4Ckd6QVpCZ05WQkFNVEVtVjBZMlF0YldWMGNtbGpMWE5wWjI1bGNqQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQUQKZ2dFUEFEQ0NBUW9DZ2dFQkFMd0ZoMnBuZy9zNDFZREliQVErSU8vNGRJMU5mUlhsYWNZT3dCZm11MzVTUERoeQpET3FUY1k1YzZxMzBnZDhwUUNyZENzRGhIV2FEdlVuSWQzelNvWkpHZWtyTGNSVWpCZnE3QkphaVZoRlBEa1RFCmdMSmlxaC9kWks3Rlo5dDE3bmdkaDl1OW81VWtTZ0hrOC9HZmpSTUVLNWdxMWtJQlVjaHc3Z0ppNlo4VWpzMHoKV2svcXZVWlpxTUp5eFA0SHM0UzJud0RBQmNjNXdWakhGUkRjNXJrcnF6UFhkc2xCTVR5cWZ0TXFWY2RFOGh2YwpxbUkrNlB0WEEzZTNEU0cvSjIvVG5ablBmRVRSM1ZKQ0NXYWVvRDFEemxWbGZPNjB1LzVYSzViN3g5cW1HTndrCjlYME4zVGJxZFlDZEg0K0xUYzQ5U2hIZ1djaWs0ZlpFV0Q2T09JMENBd0VBQWFOQ01FQXdEZ1lEVlIwUEFRSC8KQkFRREFnS2tNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGSlFkK2YrQ3Y2Y1ljRmNwZDF4RQpTQThxeEt0eU1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQXo2VkZNTzFLOUdmMGZ1YmVVZjJ1cGF0TithUEgzCnE2MFJIMUo2Rmc5ZTdXTWNqZHowMk1RVmVpRm1jcmZDSjMwSVhBb3RTOVZpamFRWnNteFUvSGIxV3hrcmJBL28KdUxQdnU5UzZ3TEFHb2grUXlGWWhXN0ZzdVR6KzIrSExremVxVXpkZllXRm5KRXlHYjRPdDRDdjJRY2M4T1FQWQpqTUorcGdWbENDeUZXRCtWRCtreC92MkE5VThya1JGTDdmZkJ0NlZtRWNLcWkwRHNZSFdJNEpqUmpXeXhzWmhpClArSHdIU0todWdZUnVZQXYwVkl1eVBMVjRPT0RJRVJCU2MwWi8wVXgvUEY0YWwvK1NrSVdyTkZQZkVyWm5GaXMKQ21LMjMzNTFleHNJZjZhMjBTc25WSnVLSVFGR1h6aDRqVU9PNHdNdTR5M2tkL0NsNTJxNElIa2oKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  etcd-client.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURWRENDQWp5Z0F3SUJBZ0lJUTVtN3R3M29LcXN3RFFZSktvWklodmNOQVFFTEJRQXdNVEVTTUJBR0ExVUUKQ3hNSmIzQmxibk5vYVdaME1Sc3dHUVlEVlFRREV4SmxkR05rTFcxbGRISnBZeTF6YVdkdVpYSXdIaGNOTWpBdwpOREUwTVRRd05qQTRXaGNOTXpBd05ERXlNVFF3TmpBNFdqQXNNUlF3RWdZRFZRUUxFd3RsZEdOa0xXMWxkSEpwCll6RVVNQklHQTFVRUF4TUxaWFJqWkMxdFpYUnlhV013Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUUN1ZjVLUDZsWTRYbDkzMVErN3VJaFQxK2ZCdjByS0VWOWhQQW9MbFFtQkI0bFpmWVpRREdieQpzcDJGVTZXcTFsUVU2VTdvMHpkaTlVVnErV25qdGVCdHZ1UWpCanVtVzhWd3lqNHRySXhFc3NUZnRhaER0S0VyCmVXUnZaK21aSTg2UEYrUUxGWnJNUGEyYmlvT25KNVhBelVGcDFpT05EeldTNFZud0xYbjRjUS8xdkpzMWsyQVQKQzY4MmV4dWN2UUUwYU16WHU5eW9TRlp2QnQ2MitGcEhpM1ZaSnBweDBPclRURlhXV1dFZ3VKNGVObG4ycHBsTAo5MHVabnVibVgvSk9kZFpudUN2dEZXSTAreC9OeXlpcWEzLzVsUFZmaFhlSGNRVFRKNFg0MUl1UGh6NkIya20yCmhnWjRHMXpQT21vN2QzblpCMURLc1JtbGFaaEIwT2VIQWdNQkFBR2pkVEJ6TUE0R0ExVWREd0VCL3dRRUF3SUYKb0RBVEJnTlZIU1VFRERBS0JnZ3JCZ0VGQlFjREFqQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJTVQpIZm4vZ3IrbkdIQlhLWGRjUkVnUEtzU3JjakFmQmdOVkhTTUVHREFXZ0JTVUhmbi9ncituR0hCWEtYZGNSRWdQCktzU3JjakFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBRGdmNjNSenpkNWtqTHkzdkorTWQ5NHBJN1RlWFh1Tm4KNVk5STN4RTRvWHhSa0lQMDIwMGhpR3hVQlJtR3ZHaHpLTnd5a3MrcmdxVjJTV1ptYW9xQ2JndlZOK056V2ZveApodnhoRUxpbWE3YmtSVEp3bkZIVStuRkNMTzczWTY1Nkxyc1VBTWxPam5SSjZUcGgveXNUcUd6WE84VGZ5ampUCkhjZXh3bUNPazl1MUZ2ZGxGclJOK0t0UG5IejJVM3I3a0dodXBJdE42emRFcCtsMVZLbDVlVHFiSmUyd3BpSUoKWlRPUXUyOSs4QUtBVS9vYnVqVkVCeVR2emw1c2kyMkc3RUk3ZVNDTmpjK1JnRjJ1QWhlcG4vb1RPWk5VRUYwbwo5TEI4ZEg5Y25DdGU5SGNCV3R3RDhudlRNMjhzYlN4eXhwK3BwYkwwQWVMbnUrYnhKUFo5WGc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  etcd-client.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBcm4rU2orcFdPRjVmZDlVUHU3aUlVOWZud2I5S3loRmZZVHdLQzVVSmdRZUpXWDJHClVBeG04cktkaFZPbHF0WlVGT2xPNk5NM1l2VkZhdmxwNDdYZ2JiN2tJd1k3cGx2RmNNbytMYXlNUkxMRTM3V28KUTdTaEszbGtiMmZwbVNQT2p4ZmtDeFdhekQydG00cURweWVWd00xQmFkWWpqUTgxa3VGWjhDMTUrSEVQOWJ5YgpOWk5nRXd1dk5uc2JuTDBCTkdqTTE3dmNxRWhXYndiZXR2aGFSNHQxV1NhYWNkRHEwMHhWMWxsaElMaWVIalpaCjlxYVpTL2RMbVo3bTVsL3lUblhXWjdncjdSVmlOUHNmemNzb3FtdC8rWlQxWDRWM2gzRUUweWVGK05TTGo0YysKZ2RwSnRvWUdlQnRjenpwcU8zZDUyUWRReXJFWnBXbVlRZERuaHdJREFRQUJBb0lCQUMyeXRTUkJYMkVWdmZTNAo5SXpaejhIOVdmRlFjbnFtd0E3TDFXbWhGME1XUVM4UmczbzFOVVM3NkNyQmRESmdQTmJaSHRRMGRGM1RFK0htCi9ZY24yMldDUjJhd3ZEQmQra0FHaHZBWkx3YlN0bUpMeFl3dG9zT3EzOVdaSmdEMzhxRmd4VlR0eklOT1o4ZkQKSjZVLzVhVC9XL0VtcGxyTHIrRU9hU3BRRHBBMFJPQnY3WG5QcnM4ajlhK1FQV25QMXdQcWc3STZvU2o0RjB1YQpmbTFvQktQeVRVSjZGY0dZZWJEb1NIeWcwL1JBWlMyTTE0SGpIVXc3ZEJ6RmhMaDNHQ2d3S2lyTFBYSUpEd1lICkdTZVN1UzBzSk1NV2k0ZFRhc25KbTRra3RIRE1ZeTNMajRGcytubGtHUWY3MWt0VGc4ZUF5NTNiVlJIcFlBMk4KMGtaem5Ca0NnWUVBeFpXWWtJWHhFd0ZkMFFZWmhlUDFIcmw2YWVJQzl5ZWhHNWNsN3pHYVhWRXU0S0Zrb3piRgpiNnZidit1SGQ5TzFMK0ZOenhtVWNqZkU5azBCRmNBM3g5c1JEN3RoSEU4ZVNya0xQRW1BYmJsTjZOVjlmSDhRCjZiWG15WFpSMzRUbUh3UXlFTmJxSUVJUTdybjU2bGFEUUxveVNxazB0TGlNTVhYUmVhenZyQ3NDZ1lFQTRoYXUKOEdTMW96bXpwSmRjYktERE4vZGhlNU1qaWVrYTJtNmJKT1FtZy9zVGJrU2xzbUpRa1JxN1hocUg2NVR1cFlCMgpOa0FPendwbWtDNzcrUitvQjU0OThlWmJRNEZLSEx1elNIakxMSXJOcElSYWplVWp3TnQ3bjk1NnE0UklHU0hoCndXRVJYYk1RdjNDZGU1ek10c0hrVWJ5c1pYMkVOR0I5ZDZ0cldCVUNnWUJhRWx3K1poRUVEUGRydGxBa1RVc00KK3BqbmMvVE9IdTYrMlNTZDZncm94MzJMUVlmVEw4REpxNXE5M3UwZW54QldCMnVsSVpBZWtYWGtvaTRBY0dQOQpZOHhmVTVodGcxUFgxSXRlckZNenNlbm1Yb3lhR0lMcFI5Y3h1QktTeHM3eERNU1dFS01pbVh1R21KbHBUbzcvCkR1S21Ub1NNYmlUYTEwN3JIUDhWaVFLQmdRQzJuR2UwVjBPMmtQYWViSHNFYWwwRHFWWWRmOXptbVZkTk1xVXgKQ081ckQ3TEVEOEpkOExidVhNOFYxUXdQcGYyVHc4eTNTTW90UkZOUEJnUVRWaFJjQXQ0NXNqdm9yRmIyR2sxVwpyZW85RWVmRGgvdTBQRzNDYWdUU1BkcUxDbzlKYldwd3pUdy9tRkJnc0U4aTlxVUt3RlR3Q0JxZTV1Q1BoWmdSCnZtMDNlUUtCZ1FDdk40VkFOUUpmdTNLUEtWUXhrUy85NWlWOVNCWCtLS3pXUHZuajRmWDlVRHNxUGM0SUFWdXEKM3hXUlpCVlVON2MxSVRjRVNDbDBKN05aTUdQU3hQNzBOb1Q1akN1Y3JqeUYvYTU1UGlLemtUZ2x1d0dYQ1B4Zwp3M3FtNGZqK1daZG51T0ZKcURpT0JodTFRS2VxcThRVnQrT1orUFJpM041dkttNzl5c0dTL0E9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
kind: Secret
metadata:
  name: kube-etcd-client-certs
type: Opaque
---
apiVersion: v1
data:
  ca-bundle.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDXTCCAkWgAwIBAgIINOJh1jTQc+UwDQYJKoZIhvcNAQELBQAwUjFQME4GA1UE
    AwxHb3BlbnNoaWZ0LWt1YmUtY29udHJvbGxlci1tYW5hZ2VyLW9wZXJhdG9yX2Nz
    ci1zaWduZXItc2lnbmVyQDE2MDA3MzY0NDAwHhcNMjAwOTIyMDIwODUxWhcNMjAx
    MDIyMDIwODUyWjAmMSQwIgYDVQQDDBtrdWJlLWNzci1zaWduZXJfQDE2MDA3NDA1
    MzEwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC+tAYtUEqJbrf/y3tR
    3KL/htfcV4JecxiAG4TcuLBn0hxgbEFSXFAAqhFuv+POr75vBharzHeaDc6Z+RTD
    Tj/4ST4IP6uyN0rG1KwdroMdfOGKYTtvejDgNWZl38ge614bqSzc3I2t6Ccn+8K8
    Im6xDF1usIDyNzeKkukayra1FuMV0h/RARQWo9NubjskXHZWyuAc+ZKYfMueKlBg
    T43DI8PlKmPzmAPzZVbq8fi5xwNPlRTEzmW3p3vNMT3crJu5wmig2yJypnSK8kPT
    jpEJ7pHjdNXHFEeeQinCrZv8ZJ/PzI1bKW4LC8fPqIV/QgQQ5yMRS7KLR6WdZrY8
    0RVzAgMBAAGjYzBhMA4GA1UdDwEB/wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MB0G
    A1UdDgQWBBT5/AlyogV7bAOqaUuz1SsmNFTDOTAfBgNVHSMEGDAWgBTdarREzq5w
    rFw0Ip7tk6P5+iuUzzANBgkqhkiG9w0BAQsFAAOCAQEAJ23GL08mBV70UKN85MdZ
    O9HzEEIhw/OjiFcOQGhuVf9jzllQ+Rp0WPRdWXDiVZb1YI3mKGzi2W0a2M9/D53C
    Mq91xgmW1kbiDgs0vhBGO/6nzJJQwfrzMwCjNXhOEV+Zbnuj8KhP6kVVAPAR9Oew
    cQPsyJ9CRikLIhFv5diL46M0xMO3xrbHfM0U9Nx2o/M7qQIsQHcxA2YeMn8vYXtj
    w1ZcUA0M24kmoUgaVYL9lvl2MB/jkDXh0y8eY6NRmzZKpioLAMTHRqg5vjjOslxN
    mMk2mGo4iNAY7ofNIVb6GH65QXCCbRYymuRTj7Tg3Q6nIxfRMgevsJiZafGETjSt
    nA==
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDgjCCAmqgAwIBAgIBATANBgkqhkiG9w0BAQsFADBSMVAwTgYDVQQDDEdvcGVu
    c2hpZnQta3ViZS1jb250cm9sbGVyLW1hbmFnZXItb3BlcmF0b3JfY3NyLXNpZ25l
    ci1zaWduZXJAMTYwMDczNjQ0MDAeFw0yMDA5MjIwMTAwMzlaFw0yMDExMjEwMTAw
    NDBaMFIxUDBOBgNVBAMMR29wZW5zaGlmdC1rdWJlLWNvbnRyb2xsZXItbWFuYWdl
    ci1vcGVyYXRvcl9jc3Itc2lnbmVyLXNpZ25lckAxNjAwNzM2NDQwMIIBIjANBgkq
    hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyQvsDAX/U91b40lbJabMUM0Vc0mTCqxI
    swugFubvlFu+O56w+GjVi9Xd6EyvceNhIj6UMS6NCXbLeEN8PeP8j51HR2YdYc2v
    esKx7rJ/HXCqgxVKlgKZeZGjSzuGTRc30UgfHpbsmBonmZBDK82hj4Qq48GvNqiN
    oX4UpWOXXw0IkR2S/Ht4r90DecppAQ57dHgfZZ5X/lgKlbR7yPhPQSxnjwRz76xG
    kIsuHEf3HzV9A1mgT7A4vqmgveD2a6+KRGLZf2O+PrB0VyhFkbqU6vcQWKLud0e1
    HhIEpePtiYcfxiagtRpciLN61aUOnxbjwLJVakiBtT19R90xfLzxSQIDAQABo2Mw
    YTAOBgNVHQ8BAf8EBAMCAqQwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQU3Wq0
    RM6ucKxcNCKe7ZOj+forlM8wHwYDVR0jBBgwFoAU3Wq0RM6ucKxcNCKe7ZOj+for
    lM8wDQYJKoZIhvcNAQELBQADggEBAJwraMqZqJa36PsnJh3cjTYXuzdjGjb1vopl
    uIK9d/DKJok4yec6BPQEU+xNZmp1Vhz0uf1p4kLU7T2nsvbd3FXZfbdSGxpp9/+m
    ddMrYKGpmimIIeYrwTJ2C1yE3Nturwl8DxAaMExZGtGFD9SHjqna7h3DIDe4rHrg
    YGLJq5zYlSv8VobKOdxx30eXWOmt/wD7IJJb9Pbf/tBEaFibtO2O+Ixtih86QUGg
    gX4o5uwuYK5jXRjEZIuEnJQeFbcKSKwmdA/gF/SEGhOq6RYSxgoJ1Zy6GX7riqtO
    RLlAksErj6mjUODDwbgEoO8L7xaszankBgIwgJlyQ/Jlt3WWnr0=
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  name: kubelet-serving-ca-bundle
---
apiVersion: v1
data:
  service-ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDUTCCAjmgAwIBAgIIFZPkGLW2J6AwDQYJKoZIhvcNAQELBQAwNjE0MDIGA1UE
    Awwrb3BlbnNoaWZ0LXNlcnZpY2Utc2VydmluZy1zaWduZXJAMTYwMDY4NzgwMjAe
    Fw0yMDA5MjExMTMwMDFaFw0yMjExMjAxMTMwMDJaMDYxNDAyBgNVBAMMK29wZW5z
    aGlmdC1zZXJ2aWNlLXNlcnZpbmctc2lnbmVyQDE2MDA2ODc4MDIwggEiMA0GCSqG
    SIb3DQEBAQUAA4IBDwAwggEKAoIBAQDVulRveXlffAMGTRctVy8teogtRXbH9UMN
    gBOudNZEMtMEJaP7hXuKJfo2a/R/mrWCbItntjFToY8YNJC9KYtao7/VU8iCJRXM
    jl/Lx3a2993STe23aD2SuPwTdqKkhs6Io/PuEmilybWd+5SoHrae7OKm87Z0aIVM
    SqFzT3P1N9J3jIPNtjmVzYhFPJPgDlf4inDwW1fecQcxDDlkdgiIdmgkH54ydYkH
    vKUZ1Xvkbb0gu7Qn4lkggHz3euaIuZoEmhdJXZNSMoxpet+C8dtTNFrMprJPdDcP
    VOXFnqqlN7z28MSj6+OazQzlAye04WgyI6dr740/AIBhj/foGEGdAgMBAAGjYzBh
    MA4GA1UdDwEB/wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSz8878
    A9O8RlQzHtXRjeQQgkmk8DAfBgNVHSMEGDAWgBSz8878A9O8RlQzHtXRjeQQgkmk
    8DANBgkqhkiG9w0BAQsFAAOCAQEAIVai85ytcIkQulHdeUBCR2RvV0sv47FXuC4X
    WTz/kAg2NVyump7EtBqg9Td1rvl/1zFbohLKFlcBJWf54syCMd7OlpJ3H7q0QnfG
    EH6MsPSblQu6vNPSyBQcn0d1csUR+a2eGy/HmGAdfYgJm/2LrJp2JsXyT64Cfwoz
    lnZ8WUIVLn95sPPuEYJdE9VElksffoj2KF50t+P+C+8JcVidw49t13it+Y29AXIG
    dxL9MaUobjkY/FIa4SC3yhGGallbR0FSRShXin6fYJK7EW/zpM7ZYdjRHuCx9Pcn
    XrjijH0tMATayXx6VCWWRfr30VTj28k+0/buxXfAlp8brXaQtQ==
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  annotations:
    service.alpha.openshift.io/inject-cabundle: "true"
  name: serving-certs-ca-bundle
---
apiVersion: v1
data:
  etcd-client-ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKakNDQWc2Z0F3SUJBZ0lJWFZiQk9yM1JBVDh3RFFZSktvWklodmNOQVFFTEJRQXdNVEVTTUJBR0ExVUUKQ3hNSmIzQmxibk5vYVdaME1Sc3dHUVlEVlFRREV4SmxkR05rTFcxbGRISnBZeTF6YVdkdVpYSXdIaGNOTWpBdwpPVEl4TURVME56UXhXaGNOTXpBd09URTVNRFUwTnpReFdqQXhNUkl3RUFZRFZRUUxFd2x2Y0dWdWMyaHBablF4Ckd6QVpCZ05WQkFNVEVtVjBZMlF0YldWMGNtbGpMWE5wWjI1bGNqQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQUQKZ2dFUEFEQ0NBUW9DZ2dFQkFMWkhWWEY3Smd5ZXVRT1FoeTFvQWVnMkpPM0R1T2QrRmlkS05oeFpVRUF4aGJpWgp0ZDdBOXZzNzI3UmFNbzdKMWVpZmhqL3haQnlsY1NpV2w2dnZFV3FBOW13TENSOVhoZjNnRzROZWhKRkxYWGlCCm5KbUJ0ZVErempYZ3VlTUR2THJjMXRBUTl4SE1HQ3M0Y1Q0a3lMRzZjZFhuMjJHZzZ6NXhEVzNVWmxzK0V2aTgKSno1OW9CbFFJNU9kS2R5RjdNRzZPTEZ3Z203Tzl0WUdGVzVDUW5MQnMvOUl0QjVZL0cxYmJhRDlqbUQ1Mm8zZQppRkVxVVM2M3lPOUg3UkRnZmRldXJwM3JpL0thNkFucHpHc3pNSm14OTdtK2lJVDc0OUNtZlExU2YwSWpIc0JKCkJXM090WkgyUTZFMjFHNTk0cDNGZHU5NFhJa0VSaGMwSWUxYUVaRUNBd0VBQWFOQ01FQXdEZ1lEVlIwUEFRSC8KQkFRREFnS2tNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGTUFWdDNYMEVYNTFjR2dBTWlQMwpYVzRpYTQ2YU1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQTBXUm5HbjV0TVBuK21kUHJobFpQdEJ1dmRJYTJZClB5Z0JPSmwzaTk2Z2ZFcGoxYnZxSUlRVEdpNWpxMGx3VmxBZVhBcEt6TzZka0FUVG9pRXpkOEs3ZG5PRmN5VkUKQjBKcGZqTyswYWdKb0swN2Q0VEFJWHJiUkpXby9PcnpFWlptbElFdkE5VnlHY1lVekpjR040TnJ3SndQeDY2aQpQVHpxWlZQWkNuekh5NWVTa1h3TlZNU3BrOWRvVHJOV3NVa2lEOGVIYzBIMCtxT2xpa3QzcDVXWCt3c1QyS1RaCkcxT1ZCQWdwRmU4aUVsZ3A4RWpKbk5LdksyT253bFN2VXduRTA1Q2NEWU5pS3IwTGM3aVN1SmpqY1BTbUt4WDEKVFFNZUd5akZiR0IrdGE2L1dpVkllY0JtUHVsVzYzTmZ0SmlLK1FOR3BaN1U0OEp1N1gyVktOaHcKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  etcd-client.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURWRENDQWp5Z0F3SUJBZ0lJS3FFMTBTWnRmSTh3RFFZSktvWklodmNOQVFFTEJRQXdNVEVTTUJBR0ExVUUKQ3hNSmIzQmxibk5vYVdaME1Sc3dHUVlEVlFRREV4SmxkR05rTFcxbGRISnBZeTF6YVdkdVpYSXdIaGNOTWpBdwpPVEl4TURVME56UXhXaGNOTXpBd09URTVNRFUwTnpReFdqQXNNUlF3RWdZRFZRUUxFd3RsZEdOa0xXMWxkSEpwCll6RVVNQklHQTFVRUF4TUxaWFJqWkMxdFpYUnlhV013Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUURsbERoZ0tCNE0xNGhQTU4zRmpjNUlPYWhZTkJVbXJoZVhUZFhCR0ZDbEdmb0R3aERKWW9lNgpxTHEraUEvYlNEcXRvU2VIc0pzS05IZU9FWC9DQ3V3R295SXhLRXJNTXAxVEtDbTkxaGdydEN3MnFSVUtpZzlxCkl6RmhGT0tkOUJxNm1zZGkxelp3Wm5SRzJJVkdwMEtad2M3RTFDWGlqQzVvRjNPL1VkbDIrT2NrRE5pQ1EvZGgKWSszMnBXcUdySng3aGMyOU95N2liWmtaUlVGa210UHk4VVY0MjJ5amJMNjJON3NVSUZIalBTWVJudk5zUzJ1OAoxMUJNU2hLMFVyZUNtZCthR1JScFNJQTVrbm4za0grWHpwVWhIcnFnQlhFajVDNUtOVVRmV3ZnTzNCM0FRVWFTCmpwYjlQSThvUVQvRHkvOTFSRGxqemRYOGx1RVovOHFiQWdNQkFBR2pkVEJ6TUE0R0ExVWREd0VCL3dRRUF3SUYKb0RBVEJnTlZIU1VFRERBS0JnZ3JCZ0VGQlFjREFqQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJUNgptUlVnTFllTGNqTmREUUJFYkRLTm80SXRvekFmQmdOVkhTTUVHREFXZ0JUQUZiZDE5QkYrZFhCb0FESWo5MTF1CkltdU9takFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBU0lQY3JSNjlSRzViR1R2MTZCenMzZklvYW5zbUdKbkEKL1hEWGhmR2oybDlYWk9TYmI4OXlJSFMvZVkzMWdoT0hnWFlraXhQOTZXYm8xL3kxWm5UTnpzRmRBalFDVnRFVgo0bFBjK1BUbm14YTlWZXlvYjJmV2ZOSERhd0NLZTVEL09KT1BuNG5rWXZrUFhXRFFERGFpd2RuUkxTN093dlJICmtCQjE4YzJEb2NEZURPMDZ4bjNVaWxubTFxNjVQVzc2MUE3VkdaSHJHUklrV044ZHhvTEtSa1FveTBPcmt2aEcKT1M1VDN3R0kxNnZlWERDWWcxV1NiTUlVTWNKV1dETzhOUjhUTkVvTmo4OUZGQmpSYWtrejYrNjNLVzMyQkVLRgpuRnNIMDdQSDg4eUJvb3VJVGpvdTk3UC9PNGJRVzNMcUJTdVRiT3hmVDlCN1R4YmI0bGV2NkE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  etcd-client.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBNVpRNFlDZ2VETmVJVHpEZHhZM09TRG1vV0RRVkpxNFhsMDNWd1JoUXBSbjZBOElRCnlXS0h1cWk2dm9nUDIwZzZyYUVuaDdDYkNqUjNqaEYvd2dyc0JxTWlNU2hLekRLZFV5Z3B2ZFlZSzdRc05xa1YKQ29vUGFpTXhZUlRpbmZRYXVwckhZdGMyY0daMFJ0aUZScWRDbWNIT3hOUWw0b3d1YUJkenYxSFpkdmpuSkF6WQpna1AzWVdQdDlxVnFocXljZTRYTnZUc3U0bTJaR1VWQlpKclQ4dkZGZU50c28yeSt0amU3RkNCUjR6MG1FWjd6CmJFdHJ2TmRRVEVvU3RGSzNncG5mbWhrVWFVaUFPWko1OTVCL2w4NlZJUjY2b0FWeEkrUXVTalZFMzFyNER0d2QKd0VGR2tvNlcvVHlQS0VFL3c4di9kVVE1WTgzVi9KYmhHZi9LbXdJREFRQUJBb0lCQURSVS9DRFhKRHB6S3d3NgpMR05xOXJtNkF1alFQbjRKc3pEM09pR0JCR2tPS2RLUGV6b2NycW5hNm02aUgxTXgvTVkxZFFoV05wRTE4b2E4CjhHMXdCZXRoWmxya1AyQ2FyUWdXb0tVNFYxd20vdWthMDhRS1FvZEVMRzVmejJTSUQwdTRHbmtxYTZ0bGYxM2kKMzBhQ3ZBakdoL2FRRVc2NTI1NDRzbGJMTnBJS3JqY3FaUnhxbi9YZGhyblphOVY3eUV4cHFvL240ODRiL1h2Ywp4RFo3ZzdBQU9WVTA2aUpNUGNKL1VxQ0kxWTNVNWFJVjk0eVpPU29wOFRvWjA0VzR5MnJUbndoaWd6cXlGNWZBClJaOTdLVXVIZmhqUFdYWTZ6Si9CSno1cGFpbGxPNTlicmRmOVE1YjBXUGVDR3BCa3VtRDd5ZXJtV3JMNWZib0oKNjNIYUFsRUNnWUVBNmxpVGkwY3JyYmZFbldsUTVPaUpJZTlCeVBJdVZTY3hHQVhyWWU0bGN2aDQ4OFkzL2wvZgpkTVZKQmd5SjVQQkdRem1aVkFIdENBWHRNNXEyL1RMUmdvUkg4NW40NlJ2RldQSlFjQXZJTlhCbHFnTkNUOVFECmtkVVRoRTRRN0N4RXV4SERDODRhUFZDcE42L3dFZnRaOFB2dmttcWlTT2lheU83d25iSzluYmtDZ1lFQStzcmgKZUFZSE1rTllIcjlVM3I3YnhFeW4rYnI4VmdWNWUzbDZ2VGhUcHN6YXd3TmRFQ0ZYWUhyY2pyL2RNbnhOOXhDbAp0My9nOUppRFJTYmZPaTkzc2FaWFg2ZFZObmpjbmcyWXNONGNmQUpIYkZxVnFCRUxrdkJVUEttVnVsaUR0SGhuCjdacjZYbkJBT3diWm13a1p4emhPa3FsQ1Y3QVltUHJPTjR5RnRQTUNnWUVBakk2TUVHR2pwUkl2NzJvWGh2U2kKSzZSaGhMRWRjUjJNcUtnRVFqeWdZWkQrbXRndEJYbGpnWnBDN2tuZSsxM1NCc2dwV3VXODBhOGNVbk5kaGdoUQorVU4yRkhvcGZVZVcybjZjR0ZnNHdUU2xCWS9tMmhLRUFaZ1htS2RxSnYxMlMrMmZXeGxIUzdkeGgyRVRVUFc5ClFIa2JmR3BRNUFIL3RMejd2TnBVT0tFQ2dZQkFFeVdYN0xKWi9TcStjRlBXdFJ5aEFwVElFU1gzTkY3ZFZTUXUKdy8xYldHdHI5NmdIUHYxOEFPZm84TXdxNGVkcGdDOVd1cTFXME1CNUluMVYrRnEwWUxOaUZQYUlmRWloZVFmUgo2RzJPb1dadUlKYXI0ZTc3RTd2eDQ4SUZZaWdFSzk4aHJiN1o4Z1AzRU1ENEExTTZ1d0FZS0haeXdPTUg4c3hOCkZQSDBVUUtCZ0NqczVlWVZPdUY4QXhGYzQrNVFqMmszUXNpclRnUHhWcjJ3STd4d0dla3ZJWjZZRUxlVE5lcTcKUjc5K0YyNVNSMGVCUW95ODZBK1Z4bXIvQmhqNmZrUFVUUUpFcFBwS0Y5QXdXN0grTm82bWc3TFh5RHRmWWErcApTR2VhSlVGeFZ1cTBXOU1hTm5BZXRlTXBIeE9pOFo5RW5hR1VwRFZ1SHVEU2hRZUdUZHpvCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
kind: Secret
metadata:
  name: kube-etcd-client-certs
type: Opaque
