apiVersion: v1
kind: Service
metadata:
  name: {{ include "telegraf-switch.fullname" . }}
  labels:
    {{- include "telegraf-switch.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      #nodePort: 30273
      targetPort: 9273
      protocol: TCP
      name: http
  selector:
    {{- include "telegraf-switch.selectorLabels" . | nindent 4 }}
