---
# Source: telegraf/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-{{ .Chart.Name }}
  labels:
    app.kubernetes.io/name: telegraf
data:
  telegraf.conf: |+

    [agent]
      interval = "10s"
      round_interval = true
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      collection_jitter = "0s"
      flush_interval = "5s"
      flush_jitter = "0s"
      precision = ""
      debug = true
      quiet = false
      hostname = {{ quote .Chart.Name }}
      omit_hostname = false
    
    [[inputs.mem]]
      [inputs.mem.tags]
        datacenter_id = {{ quote .Values.qct.datacenterID }}
        room_id = {{ quote .Values.qct.roomID }}
        rack_id = {{ quote .Values.qct.rackID }}
        server_id = {{ quote .Values.qct.serverID }}
    
    [[inputs.cpu]]
      ## Whether to report per-cpu stats or not
      percpu = false
      ## Whether to report total system cpu stats or not
      totalcpu = true
      ## If true, collect raw CPU time metrics.
      collect_cpu_time = false
      ## If true, compute and report the sum of all non-idle CPU states.
      report_active = false
      [inputs.cpu.tags]
        datacenter_id = {{ quote .Values.qct.datacenterID }}
        room_id = {{ quote .Values.qct.roomID }}
        rack_id = {{ quote .Values.qct.rackID }}
        server_id = {{ quote .Values.qct.serverID }}
    
    [[inputs.diskio]]
      device_tags = ["ID_PART_ENTRY_NUMBER", "ID_TYPE"]
      [inputs.diskio.tags]
        datacenter_id = {{ quote .Values.qct.datacenterID }}
        room_id = {{ quote .Values.qct.roomID }}
        rack_id = {{ quote .Values.qct.rackID }}
        server_id = {{ quote .Values.qct.serverID }}

    [[inputs.smart]]
      attributes = true

    [[outputs.prometheus_client]]
      # metric_version = 2
      listen = ":9273"
      path = "/metrics"
      expiration_interval = "60s"
