apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "telegraf-server-local.fullname" . }}
  labels:
    {{- include "telegraf-server-local.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "telegraf-server-local.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "telegraf-server-local.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "telegraf-server-local.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      hostNetwork: true
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: HOST_PROC
            value: "/hostfs/proc"
          volumeMounts:             
          - name: config            
            mountPath: /etc/telegraf
          - name: dev
            mountPath: /dev
          - name: proc
            mountPath: /hostfs/proc
          - name: udev
            mountPath: /run/udev
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            privileged: true
      volumes:                   
        - name: config             
          configMap:               
            name: telegraf-{{ .Chart.Name }}
            nodeSelector:
      #{{- with .Values.nodeSelector }}
        #{{- toYaml . | nindent 8 }}
      #{{- end }}
        - name: dev
          hostPath:
            path: /dev
        - name: proc
          hostPath:
            path: /proc
        - name: udev
          hostPath:
            path: /run/udev
      affinity:
        nodeAffinity:                                    
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:                           
            - matchExpressions:                          
              - key: kubernetes.io/hostname              
                operator: In                             
                values: 
                - {{ .Chart.Name }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
