apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "elasticsearch.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.master.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "elasticsearch.fullname" . }}-discovery
spec:
  type: NodePort
  ports:
    - port: 9200
      targetPort: 9200
      nodePort: 30200
  selector:
    app: {{ template "elasticsearch.name" . }}
    component: "{{ .Values.master.name }}"
    release: {{ .Release.Name }}
