{
 "title": "5G Core",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "vpp_interface_rx_miss{interface=\"local0\"}"
   }
  ]
 },
 "panels": [
  {
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum((rate(vpp_interface_tx_bytes{interfaceTag=~\"NWI0-N(3|6).*\"}[1m]) *8 ) / (1024^3))"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(rate(vpp_interface_tx_bytes{interfaceTag=\"NWI0-N6\",job=\"upf-agent\"}[1m] )* 8) / (1024^3)"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(rate(vpp_interface_tx_bytes{interfaceTag=\"NWI0-N6\",job=\"upf-agent\"}[1m] )* 8) / (1024^3)",
     "legendFormat": "UL"
    },
    {
     "expr": "(rate(vpp_interface_tx_bytes{interfaceTag=\"NWI0-N3N9\",job=\"upf-agent\"}[1m] )* 8) / (1024^3)",
     "legendFormat": "DL"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(vpp_interface_tx_packets{interfaceTag=\"NWI0-N6\"}[1m])",
     "legendFormat": "UL"
    },
    {
     "expr": "rate(vpp_interface_tx_packets{interfaceTag=\"NWI0-N3N9\"}[1m])",
     "legendFormat": "DL"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(rate(vpp_interface_tx_bytes{interfaceTag=\"NWI0-N3N9\",job=\"upf-agent\"}[1m] )* 8) / (1024^3)"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "0", "legendFormat": "Attach" },
    { "expr": "0", "legendFormat": "Detach" }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "0" }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "vpp_upf_sessions", "legendFormat": "Attach Success" }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(vpp_interface_rx_miss{interfaceTag=\"NWI0-N6\"}[1m])",
     "legendFormat": "UL"
    },
    {
     "expr": "rate(vpp_interface_rx_miss{interfaceTag=\"NWI0-N3N9\"}[1m])",
     "legendFormat": "DL"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(vpp_interface_tx_bytes{interfaceTag=\"NWI0-N3N9\",job=\"upf-agent\"}[1m] ) / rate(vpp_interface_tx_packets{interfaceTag=\"NWI0-N3N9\"}[1m])"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "query": "_index:\"5g*\"",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}
{
 "title": "NFVD-DC",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datacenter_id", "query": "20" }
  ]
 },
 "panels": [
  { "title": "Room Information", "type": "text", "gridPos": { "h": 14, "w": 12, "x": 0, "y": 0 }, "content": "\n\n\n\n" },
  { "title": "Device Health Status", "type": "text", "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 }, "content": "\n\n\n\n\n" },
  { "title": "Power Usage Effectiveness", "type": "text", "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 }, "content": "\n\n\n\n\n" },
  {
   "type": "singlestat",
   "description": "Network Throughput",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 8 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(qct_switch_rx_bytes{datacenter_id=\"$datacenter_id\"}[2m]))+sum(irate(qct_switch_tx_bytes{datacenter_id=\"$datacenter_id\"}[2m]))"
    }
   ]
  },
  {
   "type": "graph",
   "description": "Network Throughput",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(qct_switch_tx_bytes{datacenter_id=\"$datacenter_id\"}[2m]))",
     "legendFormat": "Total TX of Devices"
    },
    {
     "expr": "sum(irate(qct_switch_rx_bytes{datacenter_id=\"$datacenter_id\"}[2m]))",
     "legendFormat": "Total RX of Devices"
    }
   ]
  },
  {
   "type": "singlestat",
   "description": "Power Consumption",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 14 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(ipmi_sensor{datacenter_id=\"$datacenter_id\",sensor_name=~\"psu.+input\"})+sum(qct_switch_power{datacenter_id=\"$datacenter_id\"}))/1000"
    }
   ]
  },
  {
   "type": "graph",
   "description": "Power Consumption",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 14 },
   "yaxes": [
    { "format": "kwatt" }
   ],
   "targets": [
    {
     "expr": "(sum(ipmi_sensor{datacenter_id=\"$datacenter_id\",sensor_name=~\"psu.+input\"})+sum(qct_switch_power{datacenter_id=\"$datacenter_id\"}))/1000",
     "legendFormat": "Total Power Consumption of Devices"
    }
   ]
  },
  {
   "type": "singlestat",
   "description": "Temperature",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 14 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(ipmi_sensor{datacenter_id=\"$datacenter_id\",sensor_name=\"temp_inlet\"})"
    }
   ]
  },
  {
   "type": "graph",
   "description": "Temperature",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "avg(ipmi_sensor{datacenter_id=\"$datacenter_id\",sensor_name=\"temp_inlet\"})",
     "legendFormat": "Average Temperature of Devices"
    }
   ]
  },
  {
   "type": "table",
   "description": "Event Log",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 25 },
       "type": "raw_document"
      }
     ],
     "query": "DC_ID: $datacenter_id",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}
{
 "title": "OCP",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(up{job=\"kubernetes-apiservers\"} == 1) / count(up{job=\"kubernetes-apiservers\"})) * 100"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(up{job=\"kube-controller-manager\"} == 1) / count(up{job=\"kube-controller-manager\"})) * 100"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(up{job=\"scheduler\"} == 1) / count(up{job=\"scheduler\"})) * 100"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(etcd_server_has_leader{service=\"etcd\"} == 1) / count(etcd_server_has_leader{service=\"etcd\"} )) * 100"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(up{namespace=\"kube-system\",service=\"kubelet\"} == 1) / count(up{namespace=\"kube-system\",service=\"kubelet\"})) * 100"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(up{job=\"scheduler\"} == 1) / count(up{job=\"scheduler\"})) * 100"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "count(kube_node_info)" }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "count(kube_namespace_created)" }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "count(kube_pod_created)" }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "count(kube_pod_container_info)" }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{phase=\"Pending\"} == 1) or vector(0)"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (sum(kube_node_status_capacity_pods) - sum(kube_pod_info)) / sum(kube_node_status_capacity_pods) * 100"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(1 - sum(rate(apiserver_request_count{code=~\"2..\"}[5m])) / sum(rate(apiserver_request_count[5m]))) * 100",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(1 - sum(rate(apiserver_request_count{code=~\"2..\"}[5m])) / sum(rate(apiserver_request_count[5m]))) * 100",
     "legendFormat": "API Fail Rate"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ALERTS_FOR_STATE{alertname=\"KubePodCrashLooping\"}) or vector(0)"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(ALERTS_FOR_STATE{alertname=\"KubePodCrashLooping\"}) or vector(0)",
     "legendFormat": "Crashlooping Pods"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(instance:node_cpu_utilisation:rate1m) / count(instance:node_cpu_utilisation:rate1m)) * 100",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(instance:node_cpu_utilisation:rate1m)*100",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(instance:node_memory_utilisation:ratio)) / count(instance:node_memory_utilisation:ratio) * 100"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(instance:node_memory_utilisation:ratio)*100",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(rate(node_network_receive_bytes_total{device=~\"enp.*\"}[5m]) >0) *8 ) / 1000^2"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(node_network_receive_bytes_total{device=~\"enp.*\"}[5m]) >0) *8 ) / 1000^2",
     "legendFormat": "Throughput"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(instance:node_filesystem_usage:sum)/sum(node_filesystem_size_bytes{mountpoint=\"/\",device=~\"/dev/.+\"})*100"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(instance:node_filesystem_usage:sum)/sum(node_filesystem_size_bytes{mountpoint=\"/\",device=~\"/dev/.+\"})*100",
     "legendFormat": "Disk Usage"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 20 },
       "type": "raw_document"
      }
     ],
     "query": "_index:\"host\\-system*\"",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}
{
 "title": "ONAP",
 "time": { "from": "2020-01-17T13:21:13.829Z", "to": "2020-01-22T15:45:24.735Z" },
 "panels": [
  {
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "Watt" }
   ],
   "targets": [
    {
     "alias": "Max Performance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Aipower",
     "select": [
      [
       { "params": [ "max_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Power Consumption",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Aipower",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "Gbits", "label": "Predicted Traffic" }
   ],
   "targets": [
    {
     "alias": "Numbers of VNFs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Aipower",
     "select": [
      [
       { "params": [ "vnf_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Predicted Traffic",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Aipower",
     "select": [
      [
       { "params": [ "t_predict" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "Gbits", "label": "Predicted Traffic" }
   ],
   "targets": [
    {
     "alias": "CPU Speed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Aipower",
     "select": [
      [
       { "params": [ "speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Predicted Traffic",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Aipower",
     "select": [
      [
       { "params": [ "t_predict" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}
{
 "title": "NFVD-Rack",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "rack_id", "query": "22" }
  ]
 },
 "panels": [
  { "title": "Device Information", "type": "text", "gridPos": { "h": 20, "w": 10, "x": 0, "y": 0 }, "content": "\n\n\n\n" },
  { "title": "Device Health Status", "type": "text", "gridPos": { "h": 8, "w": 7, "x": 10, "y": 0 }, "content": "\n\n\n" },
  { "title": "Capacity", "type": "text", "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 }, "content": "\n\n" },
  {
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(ipmi_sensor{rack_id=\"$rack_id\",sensor_name=~\"psu.+input\"})+sum(qct_switch_power{rack_id=\"$rack_id\"}))/1000"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 8 },
   "yaxes": [
    { "format": "kwatt" }
   ],
   "targets": [
    {
     "expr": "(sum(ipmi_sensor{rack_id=\"$rack_id\",sensor_name=~\"psu.+input\"})+sum(qct_switch_power{rack_id=\"$rack_id\"}))/1000",
     "legendFormat": "Total Power Consumption of Devices"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 14 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(ipmi_sensor{rack_id=\"$rack_id\",sensor_name=\"temp_inlet\"})"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 14 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "avg(ipmi_sensor{rack_id=\"$rack_id\",sensor_name=\"temp_inlet\"})",
     "legendFormat": "Average Temperature of Devices"
    }
   ]
  },
  {
   "type": "table",
   "description": "Event Log",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 25 },
       "type": "raw_document"
      }
     ],
     "query": "_index:\"syslog*\"",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}
{
 "title": "NFVD-Room",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "room_id", "query": "21" }
  ]
 },
 "panels": [
  { "title": "Rack Information", "type": "text", "gridPos": { "h": 14, "w": 10, "x": 0, "y": 0 }, "content": "\n\n\n" },
  { "title": "Device Health Status", "type": "text", "gridPos": { "h": 8, "w": 7, "x": 10, "y": 0 }, "content": "\n\n\n" },
  { "title": "Power Usage Effectiveness", "type": "text", "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 }, "content": "\n\n\n\n" },
  {
   "type": "singlestat",
   "description": "Network Throughput",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 8 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(qct_switch_rx_bytes{room_id=\"$room_id\"}[2m]))+sum(irate(qct_switch_tx_bytes{room_id=\"$room_id\"}[2m]))"
    }
   ]
  },
  {
   "type": "graph",
   "description": "Network Throughput",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(qct_switch_tx_bytes{room_id=\"$room_id\"}[2m]))",
     "legendFormat": "Total TX of Devices"
    },
    {
     "expr": "sum(irate(qct_switch_rx_bytes{room_id=\"$room_id\"}[2m]))",
     "legendFormat": "Total RX of Devices"
    }
   ]
  },
  {
   "type": "singlestat",
   "description": "Power Consumption",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 14 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(ipmi_sensor{room_id=\"$room_id\",sensor_name=~\"psu.+input\"})+sum(qct_switch_power{room_id=\"$room_id\"}))/1000"
    }
   ]
  },
  {
   "type": "graph",
   "description": "Power Consumption",
   "gridPos": { "h": 7, "w": 9, "x": 3, "y": 14 },
   "yaxes": [
    { "format": "kwatt" }
   ],
   "targets": [
    {
     "expr": "(sum(ipmi_sensor{room_id=\"$room_id\",sensor_name=~\"psu.+input\"})+sum(qct_switch_power{room_id=\"$room_id\"}))/1000",
     "legendFormat": "Total Power Consumption of Devices"
    }
   ]
  },
  {
   "type": "singlestat",
   "description": "Temperature",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 14 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(ipmi_sensor{room_id=\"$room_id\",sensor_name=\"temp_inlet\"})"
    }
   ]
  },
  {
   "type": "graph",
   "description": "Temperature",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 14 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "avg(ipmi_sensor{room_id=\"$room_id\",sensor_name=\"temp_inlet\"})",
     "legendFormat": "Average Temperature of Devices"
    }
   ]
  },
  {
   "type": "table",
   "description": "Event Log",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 25 },
       "type": "raw_document"
      }
     ],
     "query": "_index:\"syslog*\"",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}
{
 "title": "NFVD-Server",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "serial_number", "query": "QTFCR28450165, QTFCR2725007B" },
   { "name": "server_id", "query": "27,28,29,30" }
  ]
 },
 "panels": [
  {
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "cpu_usage_idle{cpu=\"cpu-total\",server_id=\"$server_id\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "100-cpu_usage_idle{cpu=\"cpu-total\",server_id=\"$server_id\"}",
     "legendFormat": "Load"
    }
   ]
  },
  {
   "type": "grafana-piechart-panel",
   "description": "Memory",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "mem_used_percent{server_id=\"$server_id\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "mem_available_percent{server_id=\"$server_id\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "type": "grafana-piechart-panel",
   "description": "Network",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(net_bytes_sent{server_id=\"$server_id\"}[15s]) + rate(net_bytes_recv{server_id=\"$server_id\"}[1m])) * 8 / (1024^3)",
     "legendFormat": "Used"
    },
    {
     "expr": "count(net_bytes_sent{server_id=\"$server_id\"}) * 25 * 2",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "State",
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "content": "This is server serial number:\n$serial_number\n\n\n\n"
  },
  {
   "type": "singlestat",
   "description": "Power Consumption",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 7 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ipmi_sensor{server_id=\"$server_id\",sensor_name=~\"psu.+input\"}) / 1000"
    }
   ]
  },
  {
   "type": "graph",
   "description": "Power Consumption",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 7 },
   "yaxes": [
    { "format": "kwatt" }
   ],
   "targets": [
    {
     "expr": "sum(ipmi_sensor{server_id=\"$server_id\",sensor_name=~\"psu.+input\"}) / 1000",
     "legendFormat": "Power Consumption"
    }
   ]
  },
  {
   "type": "singlestat",
   "description": "Temperature",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 7 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "ipmi_sensor{server_id=\"$server_id\",sensor_name=\"temp_inlet\",unit=\"degrees C\"}"
    }
   ]
  },
  {
   "type": "graph",
   "description": "Temperature",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "ipmi_sensor{server_id=\"$server_id\",sensor_name=\"temp_inlet\",unit=\"degrees C\"}",
     "legendFormat": "Temperature"
    }
   ]
  },
  {
   "type": "graph",
   "description": "Disk (MB/s)",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "expr": "sum(irate(diskio_read_bytes{ID_PART_ENTRY_NUMBER=\"\",ID_TYPE=\"disk\",server_id=\"$server_id\"}[2m]))/1048576",
     "legendFormat": "Disk Read"
    },
    {
     "expr": "sum(irate(diskio_write_bytes{ID_PART_ENTRY_NUMBER=\"\",ID_TYPE=\"disk\",server_id=\"$server_id\"}[2m]))/1048576",
     "legendFormat": "Disk Write"
    }
   ]
  },
  {
   "type": "graph",
   "description": "IOPs",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(diskio_reads{ID_PART_ENTRY_NUMBER=\"\",ID_TYPE=\"disk\",server_id=\"$server_id\"}[2m]))",
     "legendFormat": "Disk Read"
    },
    {
     "expr": "sum(irate(diskio_writes{ID_PART_ENTRY_NUMBER=\"\",ID_TYPE=\"disk\",server_id=\"$server_id\"}[2m]))",
     "legendFormat": "Disk Write"
    }
   ]
  },
  {
   "type": "table",
   "description": "Event Log",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 25 },
       "type": "raw_document"
      }
     ],
     "query": "_index:\"syslog*\"",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}
{
 "title": "NFVD-Switch",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "switch_id", "query": "23,24" }
  ]
 },
 "panels": [
  { "title": "Device Status", "type": "text", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 }, "content": "\n\n\n" },
  {
   "type": "grafana-piechart-panel",
   "description": "Port",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "70" },
    { "expr": "30" }
   ]
  },
  { "title": "Management Port", "type": "text", "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 }, "content": "\n\n\n\n\n" },
  {
   "title": "Capacity",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(qct_switch_interface_status{switch_id=\"$switch_id\"} == 0 or qct_switch_interface_status{switch_id=\"$switch_id\"} == 2) / count(qct_switch_interface_status{switch_id=\"$switch_id\"})"
    },
    {
     "expr": "1-(count(qct_switch_interface_status{switch_id=\"$switch_id\"} == 0 or qct_switch_interface_status{switch_id=\"$switch_id\"} == 2) / count(qct_switch_interface_status{switch_id=\"$switch_id\"}))"
    }
   ]
  },
  {
   "type": "grafana-piechart-panel",
   "description": "Discard Rate",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(qct_switch_rx_discarded_pkts{switch_id=\"$switch_id\"} + qct_switch_tx_discarded_pkts{switch_id=\"$switch_id\"})",
     "legendFormat": "Error Pkt"
    },
    {
     "expr": "sum(qct_switch_rx_pkts{switch_id=\"$switch_id\"} + qct_switch_tx_pkts{switch_id=\"$switch_id\"})",
     "legendFormat": "Pkt"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "qct_switch_cpu{switch_id=\"$switch_id\"}"
    },
    {
     "expr": "1-qct_switch_cpu{switch_id=\"$switch_id\"}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 15 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "qct_switch_memory{switch_id=\"$switch_id\"}"
    },
    {
     "expr": "1-qct_switch_memory{switch_id=\"$switch_id\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "description": "Throughput",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 15 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(qct_switch_rx_bytes{switch_id=\"$switch_id\"}[1m]) + rate(qct_switch_tx_bytes{switch_id=\"$switch_id\"}[1m]))"
    }
   ]
  },
  {
   "type": "graph",
   "description": "Throughput",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(qct_switch_rx_bytes{switch_id=\"$switch_id\"}[2m]))",
     "legendFormat": "RX"
    },
    {
     "expr": "sum(rate(qct_switch_tx_bytes{switch_id=\"$switch_id\"}[2m]))",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "type": "singlestat",
   "description": "Throughput",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(qct_switch_power{switch_id=\"$switch_id\"}) / 1000"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(qct_switch_power{switch_id=\"$switch_id\"}) / 1000",
     "legendFormat": "Power Consumption"
    }
   ]
  },
  {
   "type": "singlestat",
   "description": "Throughput",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 22 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "expr": "qct_switch_temperature_current{name=\"Temp-1\",switch_id=\"$switch_id\"}"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "qct_switch_temperature_current{name=\"Temp-1\",switch_id=\"$switch_id\"}",
     "legendFormat": "Temperature"
    }
   ]
  },
  {
   "type": "table",
   "description": "Event Log",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "query": "_index:\"switch*\"",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}
{
 "title": "vBNG",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(collectd_bng_traffic_gauge) / 1024^3"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(collectd_bng_traffic_gauge{exported_instance=\"out-rate-bits\"}/1024^3)"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(collectd_bng_traffic_gauge{exported_instance=\"out-rate-bits\"} / 1024^3)",
     "legendFormat": "in-rate-bits"
    },
    {
     "expr": "(collectd_bng_traffic_gauge{exported_instance=\"in-rate-bits\"} / 1024^3)",
     "legendFormat": "out-rate-bits"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "collectd_bng_vbras_session_gauge{bng_vbras_session=\"call-rate_pppoe\"}",
     "legendFormat": "PPPoE"
    },
    {
     "expr": "collectd_bng_vbras_session_gauge{bng_vbras_session=\"call-rate_ipoe\"}",
     "legendFormat": "IPoE"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_bng_session_gauge{exported_instance=\"pppoe\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(collectd_bng_traffic_gauge{exported_instance=\"in-rate-bits\"} / 1024^3)"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_bng_session_gauge{exported_instance=\"ipoe\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_bng_session_gauge{bng_session=\"bng-new-session-rate\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "4" }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(collectd_bng_session_gauge{bng_session=\"session_summary\",exported_instance=\"pppoe\"})",
     "legendFormat": "PPPoE"
    },
    {
     "expr": "sum(collectd_bng_session_gauge{bng_session=\"session_summary\",exported_instance=\"ipoe\"})",
     "legendFormat": "IPoE"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "collectd_bng_session_gauge{bng_session=\"bng-new-session-rate\"}",
     "legendFormat": "pppoe & ipoe"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(instance:node_cpu_utilisation:rate1m) / count(instance:node_cpu_utilisation:rate1m)) * 100"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "query": "EventType : \"vBNG\"",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}