---                                         
apiVersion: v1                              
kind: PersistentVolume                      
metadata:                                   
  name: local-storage-grafana 
  labels:                                   
    type: local                             
spec:                                       
  storageClassName: local-storage-grafana
  persistentVolumeReclaimPolicy: Retain     
  capacity:                                 
    storage: 8Gi                            
  accessModes:                              
    - ReadWriteOnce                         
  hostPath:                                 
    path: "/grafana/data/"               
