apiVersion: v1
kind: Service
metadata:
  name: {{ include "consul.fullname" . }}
  labels: {{- include "consul.labels" . | nindent 4 }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: NodePort #Ben
  ports:
    - name: rpc
      port: {{ .Values.service.rpcPort }}
    - name: serflan-tcp
      protocol: "TCP"
      port: {{ .Values.service.serflanPort }}
    - name: serflan-udp
      protocol: "UDP"
      port: {{ .Values.service.serflanPort }}
    - name: server
      port: {{.Values.service.serverPort}}
    - name: consuldns-tcp
      port: {{.Values.service.consulDnsPort}}
    - name: consuldns-udp
      protocol: "UDP"
      port: {{.Values.service.consulDnsPort}}
  #clusterIP: None #Ben
  selector: {{- include "consul.matchLabels" . | nindent 4 }}
